const TelegramBot = require("node-telegram-bot-api");
const fetch = require("node-fetch");

const TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const API_URL = "https://tele-tech-ai.onrender.com/generate";

// ✅ KA BAR WANNAN KADAI
const bot = new TelegramBot(TOKEN, { polling: true });

// /start
bot.onText(/\/start/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    "👋 Welcome to Tele Image AI!\n\n🎨 Send a text to generate image"
  );
});

// receive prompt
bot.on("message", async (msg) => {
  const chatId = msg.chat.id;
  const prompt = msg.text;

  if (!prompt || prompt.startsWith("/")) return;

  await bot.sendMessage(chatId, "🎨 Generating image, please wait...");

  try {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email: "telegram@user.com",
        prompt
      })
    });

    const data = await res.json();

    if (data.error) {
      await bot.sendMessage(chatId, "❌ " + data.error);
      return;
    }

    await bot.sendPhoto(chatId, data.image, {
      caption: "✅ Generated by Tele Image AI"
    });

  } catch (err) {
    await bot.sendMessage(chatId, "⚠️ Server error, try again later");
  }
});

console.log("🤖 Telegram bot is running...");
