const TelegramBot = require("node-telegram-bot-api");
const fetch = require("node-fetch");

// 🔐 Telegram Bot Token
const TOKEN = process.env.TELEGRAM_BOT_TOKEN;

// 🌍 URL na Tele-tech-AI
const API_URL = "https://tele-tech-ai.onrender.com/generate";

// Start bot
const bot = new TelegramBot(TOKEN, { polling: true });

bot.onText(/\/start/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    "👋 Welcome to Tele Image AI!\n\n✍️ Send me any text and I will generate an image for you."
  );
});

// Receive text prompt
bot.on("message", async (msg) => {
  const chatId = msg.chat.id;
  const prompt = msg.text;

  if (prompt.startsWith("/")) return;

  bot.sendMessage(chatId, "🎨 Generating image, please wait...");

  try {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email: "telegram@user.com",
        prompt
      })
    });

    const data = await res.json();

    if (data.error) {
      bot.sendMessage(chatId, "❌ " + data.error);
      return;
    }

    await bot.sendPhoto(chatId, data.image, {
      caption: "✅ Generated by Tele Image AI"
    });

  } catch (err) {
    bot.sendMessage(chatId, "⚠️ Server error, try again later.");
  }
});

console.log("🤖 Telegram bot is running...");
