const TelegramBot = require("node-telegram-bot-api");
const fetch = require("node-fetch");

// 🔐 Token
const TOKEN = process.env.TELEGRAM_BOT_TOKEN;

// 🌍 API URL na backend ɗinka
const API_URL = "https://tele-tech-ai.onrender.com/generate";

// ✅ START BOT (POLLING SAU ƊAYA KAWAI)
const bot = new TelegramBot(TOKEN, { polling: true });

console.log("🤖 Telegram bot is running...");

// /start
bot.onText(/^\/start/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    "👋 Welcome to *Tele Image AI*\n\n🎨 Turo rubutu (prompt) domin a ƙirƙiri hoto.",
    { parse_mode: "Markdown" }
  );
});

// Receive prompt
bot.on("message", async (msg) => {
  const chatId = msg.chat.id;
  const prompt = msg.text;

  if (!prompt || prompt.startsWith("/")) return;

  await bot.sendMessage(chatId, "🎨 Generating image, please wait...");

  try {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email: `telegram_${chatId}@user.com`,
        prompt
      })
    });

    const data = await res.json();

    if (data.error) {
      return bot.sendMessage(chatId, "❌ " + data.error);
    }

    await bot.sendPhoto(chatId, data.image, {
      caption: "✅ Generated by Tele Image AI"
    });

  } catch (err) {
    console.error(err);
    bot.sendMessage(chatId, "⚠️ Server error, try again later");
  }
});
